#SCRIPT DE CREACION

#ELIMINO LA BASE DE DATOS SI EXISTE PREVIAMENTE
DROP DATABASE IF EXISTS bddiwcurriculumvitae;

#CREACION DE LA BASE DE DATOS
CREATE DATABASE bddiwcurriculumvitae;

USE bddiwcurriculumvitae;


#CREACION DE LAS TABLAS
CREATE TABLE cvs (
	id_cv INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL,
	foto VARCHAR(255) NOT NULL,
	personal VARCHAR(255) NOT NULL,
	formativo VARCHAR(255) NOT NULL,
	laboral VARCHAR(255) NOT NULL,
	CONSTRAINT pk_referencia PRIMARY KEY (id_cv)
) CHARACTER SET utf8;

#INSERCIÓN DE DATOS EN LA TABLA
INSERT INTO cvs VALUES ('0','Nombre y Apellidos','./img/user.png','INFORMACIÓN PERSONAL','INFORMACIÓN FORMATIVO','INFORMACIÓN LABORAL');